import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Create a default clinic
  const clinic = await prisma.clinic.upsert({
    where: {
      clinicCode: 'DEFAULT-001',
    },
    update: {},
    create: {
      clinicName: 'Default Clinic',
      clinicCode: 'DEFAULT-001',
      address: 'Seoul, Korea',
      phone: '02-1234-5678',
      licenseNumber: 'LIC-2024-001',
    },
  });

  console.log('Created/Updated clinic:', clinic);

  // Create a default user
  const user = await prisma.user.upsert({
    where: {
      email: 'admin@koco.com',
    },
    update: {},
    create: {
      email: 'admin@koco.com',
      username: 'Admin User',
      passwordHash: 'default-hash', // In production, this should be properly hashed
      role: 'admin',
      clinicId: clinic.id,
      isActive: true,
    },
  });

  console.log('Created/Updated user:', user);

  // Create a default patient
  const patient = await prisma.patient.upsert({
    where: {
      patientCode: 'PAT-001',
    },
    update: {},
    create: {
      patientCode: 'PAT-001',
      patientName: 'Test Patient',
      patientBirthDate: new Date('1990-01-01'),
      gender: 'M',
      phone: '010-1234-5678',
      address: 'Seoul, Korea',
      clinicId: clinic.id,
      createdBy: user.id,
    },
  });

  console.log('Created/Updated patient:', patient);

  // Seed measurement definitions
  await seedMeasurementDefinitions();
}

async function seedMeasurementDefinitions() {
  const measurements = [
    {
      name: "SNA",
      category: "pink",
      unit: "°",
      meanValue: 81,
      titleKo: "에스엔에이",
      titleEn: "SNA",
      fullName: "Sella-Nasion-A point angle",
      description: "두개저평면(SN)과 상악골 A점이 이루는 각도로, 상악골의 전후방 위치를 평가합니다.",
      normalRangeMin: 79,
      normalRangeMax: 83,
      interpretationHigh: "상악 전돌 (Maxillary Protrusion) - 상악골이 전방으로 돌출된 상태",
      interpretationLow: "상악 후퇴 (Maxillary Retrusion) - 상악골이 후방으로 위치한 상태",
      clinicalNote: "Class II/III 부정교합 진단에 중요한 지표입니다.",
      measurementMethod: "Sella 점, Nasion 점, A point를 연결하여 형성되는 각도를 측정",
      displayOrder: 1
    },
    {
      name: "SNB",
      category: "pink",
      unit: "°",
      meanValue: 79,
      titleKo: "에스엔비",
      titleEn: "SNB",
      fullName: "Sella-Nasion-B point angle",
      description: "두개저평면(SN)과 하악골 B점이 이루는 각도로, 하악골의 전후방 위치를 평가합니다.",
      normalRangeMin: 77,
      normalRangeMax: 81,
      interpretationHigh: "하악 전돌 (Mandibular Protrusion) - 하악골이 전방으로 돌출된 상태",
      interpretationLow: "하악 후퇴 (Mandibular Retrusion) - 하악골이 후방으로 위치한 상태",
      clinicalNote: "SNA와 함께 ANB 각도를 계산하는 데 사용됩니다.",
      measurementMethod: "Sella 점, Nasion 점, B point를 연결하여 형성되는 각도를 측정",
      displayOrder: 2
    },
    {
      name: "IMPA",
      category: "pink",
      unit: "°",
      meanValue: 91,
      titleKo: "임파",
      titleEn: "IMPA",
      fullName: "Incisor Mandibular Plane Angle",
      description: "하악 전치의 장축과 하악평면이 이루는 각도로, 하악 전치의 경사도를 평가합니다.",
      normalRangeMin: 88,
      normalRangeMax: 95,
      interpretationHigh: "하악 전치 순측 경사 (Labial inclination)",
      interpretationLow: "하악 전치 설측 경사 (Lingual inclination)",
      clinicalNote: "발치/비발치 치료 계획 수립 시 중요한 지표입니다.",
      measurementMethod: "하악 전치 장축과 하악평면(Mandibular plane)이 이루는 각도를 측정",
      displayOrder: 3
    },
    {
      name: "SN",
      category: "blue",
      unit: "mm",
      meanValue: 71,
      titleKo: "에스엔",
      titleEn: "SN",
      fullName: "Sella-Nasion distance",
      description: "Sella와 Nasion 사이의 거리로, 전두개저의 길이를 나타냅니다.",
      normalRangeMin: 68,
      normalRangeMax: 74,
      interpretationHigh: "전두개저 길이 증가",
      interpretationLow: "전두개저 길이 감소",
      clinicalNote: "성장 평가 시 참고하는 기준선입니다.",
      measurementMethod: "Sella 점에서 Nasion 점까지의 직선거리를 측정",
      displayOrder: 4
    },
    {
      name: "FMA",
      category: "pink",
      unit: "°",
      meanValue: 27,
      titleKo: "에프엠에이",
      titleEn: "FMA",
      fullName: "Frankfort Mandibular Plane Angle",
      description: "프랑크푸르트 평면과 하악평면이 이루는 각도로, 수직적 안면 패턴을 평가합니다.",
      normalRangeMin: 22,
      normalRangeMax: 28,
      interpretationHigh: "Long face (개방교합 경향)",
      interpretationLow: "Short face (과개교합 경향)",
      clinicalNote: "수직적 성장 패턴 분석에 핵심적인 지표입니다.",
      measurementMethod: "FH 평면과 하악평면(Mandibular plane)이 이루는 각도를 측정",
      displayOrder: 5
    },
    {
      name: "PMA",
      category: "blue",
      unit: "°",
      meanValue: 30,
      titleKo: "피엠에이",
      titleEn: "PMA",
      fullName: "Palatal-Mandibular Angle",
      description: "구개평면과 하악평면이 이루는 각도입니다.",
      normalRangeMin: 25,
      normalRangeMax: 35,
      interpretationHigh: "수직적 성장 패턴",
      interpretationLow: "수평적 성장 패턴",
      clinicalNote: "상하악 평면 간의 관계를 평가합니다.",
      measurementMethod: "Palatal plane과 Mandibular plane이 이루는 각도를 측정",
      displayOrder: 6
    },
    {
      name: "SN-GoMe",
      category: "pink",
      unit: "°",
      meanValue: 34,
      titleKo: "에스엔-고미",
      titleEn: "SN-GoMe",
      fullName: "SN to Gonion-Menton angle",
      description: "두개저평면과 하악평면이 이루는 각도입니다.",
      normalRangeMin: 30,
      normalRangeMax: 38,
      interpretationHigh: "하악 후하방 회전 (Backward rotation)",
      interpretationLow: "하악 전상방 회전 (Forward rotation)",
      clinicalNote: "하악의 회전 패턴을 평가하는 지표입니다.",
      measurementMethod: "SN 평면과 GoMe(Gonion-Menton) 선이 이루는 각도를 측정",
      displayOrder: 7
    },
    {
      name: "FA'B'",
      category: "blue",
      unit: "°",
      meanValue: 85,
      titleKo: "에프에이비",
      titleEn: "FA'B'",
      fullName: "Facial axis angle",
      description: "안면축 각도를 나타냅니다.",
      normalRangeMin: 83,
      normalRangeMax: 88,
      interpretationHigh: "수평적 성장 패턴",
      interpretationLow: "수직적 성장 패턴",
      clinicalNote: "Rick's 분석법에서 사용되는 지표입니다.",
      measurementMethod: "Facial axis와 관련 평면이 이루는 각도를 측정",
      displayOrder: 8
    },
    {
      name: "FABA",
      category: "blue",
      unit: "°",
      meanValue: 90,
      titleKo: "파바",
      titleEn: "FABA",
      fullName: "Facial Angle of Bony A point",
      description: "골격성 A점의 안면각입니다.",
      normalRangeMin: 87,
      normalRangeMax: 93,
      interpretationHigh: "전방 안면 패턴",
      interpretationLow: "후방 안면 패턴",
      clinicalNote: "안면 프로필을 평가하는 지표입니다.",
      measurementMethod: "FH 평면과 NPog 선이 이루는 각도를 측정",
      displayOrder: 9
    },
    {
      name: "Y-angle",
      category: "blue",
      unit: "°",
      meanValue: 60,
      titleKo: "와이 앵글",
      titleEn: "Y-angle",
      fullName: "Y-axis angle",
      description: "Y축 각도로, 하악의 성장 방향을 나타냅니다.",
      normalRangeMin: 57,
      normalRangeMax: 63,
      interpretationHigh: "하악 후하방 성장",
      interpretationLow: "하악 전방 성장",
      clinicalNote: "하악 성장 방향 예측에 사용됩니다.",
      measurementMethod: "SN 평면과 SGn 선이 이루는 각도를 측정",
      displayOrder: 10
    },
    {
      name: "UGA",
      category: "blue",
      unit: "°",
      meanValue: 130,
      titleKo: "상부 하악각",
      titleEn: "UGA",
      fullName: "Upper Gonial Angle",
      description: "하악각의 상부 각도입니다.",
      normalRangeMin: 125,
      normalRangeMax: 135,
      interpretationHigh: "하악지 후방 경사",
      interpretationLow: "하악지 전방 경사",
      clinicalNote: "하악지 형태 평가에 사용됩니다.",
      measurementMethod: "Ar-Go-N 점이 이루는 상부 각도를 측정",
      displayOrder: 11
    },
    {
      name: "LGA",
      category: "blue",
      unit: "°",
      meanValue: 70,
      titleKo: "하부 하악각",
      titleEn: "LGA",
      fullName: "Lower Gonial Angle",
      description: "하악각의 하부 각도입니다.",
      normalRangeMin: 65,
      normalRangeMax: 75,
      interpretationHigh: "하악체 하방 경사",
      interpretationLow: "하악체 상방 경사",
      clinicalNote: "하악체 형태 평가에 사용됩니다.",
      measurementMethod: "N-Go-Me 점이 이루는 하부 각도를 측정",
      displayOrder: 12
    },
    {
      name: "S-A",
      category: "blue",
      unit: "mm",
      meanValue: 82,
      titleKo: "에스-에이",
      titleEn: "S-A",
      fullName: "Sella to A point distance",
      description: "Sella에서 A점까지의 거리입니다.",
      normalRangeMin: 78,
      normalRangeMax: 86,
      interpretationHigh: "상악골 전방 위치",
      interpretationLow: "상악골 후방 위치",
      clinicalNote: "상악골의 전후방 위치를 선형적으로 평가합니다.",
      measurementMethod: "Sella 점에서 A point까지의 직선거리를 측정",
      displayOrder: 13
    },
    {
      name: "UIOP",
      category: "green",
      unit: "°",
      meanValue: 8,
      titleKo: "상악 전치 교합평면각",
      titleEn: "UIOP",
      fullName: "Upper Incisor to Occlusal Plane",
      description: "상악 전치와 교합평면이 이루는 각도입니다.",
      normalRangeMin: 5,
      normalRangeMax: 12,
      interpretationHigh: "상악 전치 정출",
      interpretationLow: "상악 전치 함입",
      clinicalNote: "수직적 전치 관계를 평가합니다.",
      measurementMethod: "상악 전치 장축과 교합평면이 이루는 각도를 측정",
      displayOrder: 14
    },
    {
      name: "MOP",
      category: "blue",
      unit: "°",
      meanValue: 14,
      titleKo: "하악 교합평면각",
      titleEn: "MOP",
      fullName: "Mandibular Occlusal Plane",
      description: "하악 교합평면의 각도입니다.",
      normalRangeMin: 10,
      normalRangeMax: 18,
      interpretationHigh: "교합평면 가파름",
      interpretationLow: "교합평면 평평함",
      clinicalNote: "교합평면 경사를 평가합니다.",
      measurementMethod: "하악 교합평면과 기준평면이 이루는 각도를 측정",
      displayOrder: 15
    },
    {
      name: "FH<Ans",
      category: "blue",
      unit: "°",
      meanValue: 85,
      titleKo: "에프에이치-에이엔에스",
      titleEn: "FH<Ans",
      fullName: "FH to Anterior Nasal Spine angle",
      description: "FH 평면과 ANS가 이루는 각도입니다.",
      normalRangeMin: 82,
      normalRangeMax: 88,
      interpretationHigh: "전비극 하방 위치",
      interpretationLow: "전비극 상방 위치",
      clinicalNote: "상악골 수직적 위치를 평가합니다.",
      measurementMethod: "FH 평면에서 ANS까지의 각도를 측정",
      displayOrder: 16
    },
    {
      name: "FH<Pr",
      category: "blue",
      unit: "°",
      meanValue: 90,
      titleKo: "에프에이치-프로스티온",
      titleEn: "FH<Pr",
      fullName: "FH to Prosthion angle",
      description: "FH 평면과 Prosthion이 이루는 각도입니다.",
      normalRangeMin: 87,
      normalRangeMax: 93,
      interpretationHigh: "치조골 전방 위치",
      interpretationLow: "치조골 후방 위치",
      clinicalNote: "상악 전치부 치조골 위치를 평가합니다.",
      measurementMethod: "FH 평면에서 Prosthion까지의 각도를 측정",
      displayOrder: 17
    },
    {
      name: "Na-S-BaA",
      category: "blue",
      unit: "°",
      meanValue: 130,
      titleKo: "두개저각",
      titleEn: "Na-S-BaA",
      fullName: "Nasion-Sella-Basion angle",
      description: "두개저의 각도를 나타냅니다.",
      normalRangeMin: 125,
      normalRangeMax: 135,
      interpretationHigh: "두개저 굴곡 증가",
      interpretationLow: "두개저 굴곡 감소",
      clinicalNote: "두개저 형태를 평가하는 지표입니다.",
      measurementMethod: "Nasion-Sella-Basion 점이 이루는 각도를 측정",
      displayOrder: 18
    },
    {
      name: "Incisor Overbite",
      category: "green",
      unit: "mm",
      meanValue: 2,
      titleKo: "수직 피개",
      titleEn: "Incisor Overbite",
      fullName: "Vertical overlap of incisors",
      description: "상하악 전치의 수직적 중첩량입니다.",
      normalRangeMin: 1,
      normalRangeMax: 3,
      interpretationHigh: "과개교합 (Deep bite)",
      interpretationLow: "개방교합 (Open bite)",
      clinicalNote: "수직적 전치 관계의 핵심 지표입니다.",
      measurementMethod: "상악 전치 절단연이 하악 전치를 덮는 수직 거리를 측정",
      displayOrder: 19
    },
    {
      name: "Incisor Overjet",
      category: "green",
      unit: "mm",
      meanValue: 3,
      titleKo: "수평 피개",
      titleEn: "Incisor Overjet",
      fullName: "Horizontal overlap of incisors",
      description: "상하악 전치의 수평적 거리입니다.",
      normalRangeMin: 2,
      normalRangeMax: 4,
      interpretationHigh: "상악 전치 전돌",
      interpretationLow: "반대교합 경향",
      clinicalNote: "전후방 전치 관계의 핵심 지표입니다.",
      measurementMethod: "상악 전치 절단연에서 하악 전치 순면까지의 수평 거리를 측정",
      displayOrder: 20
    },
    {
      name: "NALA",
      category: "blue",
      unit: "°",
      meanValue: 110,
      titleKo: "비순각",
      titleEn: "NALA",
      fullName: "Nasolabial Angle",
      description: "코와 윗입술이 이루는 각도입니다.",
      normalRangeMin: 100,
      normalRangeMax: 120,
      interpretationHigh: "상순 후퇴",
      interpretationLow: "상순 돌출",
      clinicalNote: "연조직 프로필 평가에 중요한 지표입니다.",
      measurementMethod: "코 기저부와 상순이 이루는 각도를 측정",
      displayOrder: 21
    },
    {
      name: "HR",
      category: "red",
      unit: "mm",
      meanValue: 50,
      titleKo: "수평 기준선",
      titleEn: "HR",
      fullName: "Horizontal Reference",
      description: "수평 기준선입니다.",
      normalRangeMin: 45,
      normalRangeMax: 55,
      interpretationHigh: "기준선 편차",
      interpretationLow: "기준선 편차",
      clinicalNote: "측정을 위한 참조선입니다.",
      measurementMethod: "수평 기준선의 길이를 측정",
      displayOrder: 22
    },
    {
      name: "Cal",
      category: "blue",
      unit: "mm",
      meanValue: 20,
      titleKo: "두개정",
      titleEn: "Cal",
      fullName: "Calvarium length",
      description: "두개정의 길이입니다.",
      normalRangeMin: 18,
      normalRangeMax: 22,
      interpretationHigh: "두개 증가",
      interpretationLow: "두개 감소",
      clinicalNote: "두개 형태를 평가합니다.",
      measurementMethod: "두개정 부분의 길이를 측정",
      displayOrder: 23
    },
    {
      name: "ACBL",
      category: "blue",
      unit: "mm",
      meanValue: 90,
      titleKo: "전두개저 길이",
      titleEn: "ACBL",
      fullName: "Anterior Cranial Base Length",
      description: "전두개저의 길이입니다.",
      normalRangeMin: 85,
      normalRangeMax: 95,
      interpretationHigh: "전두개저 길이 증가",
      interpretationLow: "전두개저 길이 감소",
      clinicalNote: "성장 평가의 기준이 됩니다.",
      measurementMethod: "전두개저의 길이를 측정",
      displayOrder: 24
    },
    {
      name: "MBL",
      category: "blue",
      unit: "mm",
      meanValue: 70,
      titleKo: "하악체 길이",
      titleEn: "MBL",
      fullName: "Mandibular Body Length",
      description: "하악체의 길이입니다.",
      normalRangeMin: 65,
      normalRangeMax: 75,
      interpretationHigh: "하악체 과성장",
      interpretationLow: "하악체 열성장",
      clinicalNote: "하악 성장 평가에 중요합니다.",
      measurementMethod: "Go에서 Gn까지의 거리를 측정",
      displayOrder: 25
    },
    {
      name: "AFH",
      category: "blue",
      unit: "mm",
      meanValue: 120,
      titleKo: "전안면고경",
      titleEn: "AFH",
      fullName: "Anterior Facial Height",
      description: "전방 안면의 높이입니다.",
      normalRangeMin: 110,
      normalRangeMax: 130,
      interpretationHigh: "Long face",
      interpretationLow: "Short face",
      clinicalNote: "수직적 안면 패턴의 핵심 지표입니다.",
      measurementMethod: "Nasion에서 Menton까지의 수직 거리를 측정",
      displayOrder: 26
    },
    {
      name: "PFH",
      category: "blue",
      unit: "mm",
      meanValue: 80,
      titleKo: "후안면고경",
      titleEn: "PFH",
      fullName: "Posterior Facial Height",
      description: "후방 안면의 높이입니다.",
      normalRangeMin: 75,
      normalRangeMax: 85,
      interpretationHigh: "후안면 높이 증가",
      interpretationLow: "후안면 높이 감소",
      clinicalNote: "AFH/PFH 비율로 안면 패턴을 평가합니다.",
      measurementMethod: "Sella에서 Gonion까지의 거리를 측정",
      displayOrder: 27
    },
    {
      name: "E-line",
      category: "pink",
      unit: "mm",
      meanValue: -2,
      titleKo: "이라인",
      titleEn: "E-line",
      fullName: "E-line to lips",
      description: "코끝과 턱 끝을 연결한 선에서 입술까지의 거리입니다.",
      normalRangeMin: -4,
      normalRangeMax: 0,
      interpretationHigh: "입술 돌출",
      interpretationLow: "입술 함입",
      clinicalNote: "연조직 프로필의 심미성 평가 지표입니다.",
      measurementMethod: "Nose tip-Pogonion 선에서 입술까지의 거리를 측정",
      displayOrder: 28
    },
    {
      name: "Ramus height",
      category: "blue",
      unit: "mm",
      meanValue: 45,
      titleKo: "하악지 높이",
      titleEn: "Ramus height",
      fullName: "Height of mandibular ramus",
      description: "하악지의 높이입니다.",
      normalRangeMin: 40,
      normalRangeMax: 50,
      interpretationHigh: "하악지 과성장",
      interpretationLow: "하악지 열성장",
      clinicalNote: "하악 수직 성장을 평가합니다.",
      measurementMethod: "Condylion에서 Gonion까지의 거리를 측정",
      displayOrder: 29
    },
    {
      name: "Naperp-A",
      category: "blue",
      unit: "mm",
      meanValue: 0,
      titleKo: "나전-에이",
      titleEn: "Naperp-A",
      fullName: "A point to Nasion perpendicular",
      description: "Nasion 수직선에서 A점까지의 거리입니다.",
      normalRangeMin: -2,
      normalRangeMax: 2,
      interpretationHigh: "상악골 전방 위치",
      interpretationLow: "상악골 후방 위치",
      clinicalNote: "상악골 전후방 위치의 선형 평가입니다.",
      measurementMethod: "Nasion perpendicular에서 A point까지의 수평 거리를 측정",
      displayOrder: 30
    },
    {
      name: "MxBL",
      category: "blue",
      unit: "mm",
      meanValue: 95,
      titleKo: "상악 기저부 길이",
      titleEn: "MxBL",
      fullName: "Maxillary Base Length",
      description: "상악 기저부의 길이입니다.",
      normalRangeMin: 90,
      normalRangeMax: 100,
      interpretationHigh: "상악 기저부 과성장",
      interpretationLow: "상악 기저부 열성장",
      clinicalNote: "상악 성장 평가에 사용됩니다.",
      measurementMethod: "상악 기저부의 길이를 측정",
      displayOrder: 31
    },
    {
      name: "PCBL",
      category: "blue",
      unit: "mm",
      meanValue: 35,
      titleKo: "후두개저 길이",
      titleEn: "PCBL",
      fullName: "Posterior Cranial Base Length",
      description: "후두개저의 길이입니다.",
      normalRangeMin: 32,
      normalRangeMax: 38,
      interpretationHigh: "후두개저 길이 증가",
      interpretationLow: "후두개저 길이 감소",
      clinicalNote: "두개저 성장 평가에 사용됩니다.",
      measurementMethod: "Sella에서 Basion까지의 거리를 측정",
      displayOrder: 32
    },
    {
      name: "S-Por",
      category: "blue",
      unit: "mm",
      meanValue: 17,
      titleKo: "에스-포리온",
      titleEn: "S-Por",
      fullName: "Sella to Porion distance",
      description: "Sella에서 Porion까지의 거리입니다.",
      normalRangeMin: 15,
      normalRangeMax: 19,
      interpretationHigh: "거리 증가",
      interpretationLow: "거리 감소",
      clinicalNote: "측두골 위치 평가에 사용됩니다.",
      measurementMethod: "Sella 점에서 Porion까지의 거리를 측정",
      displayOrder: 33
    }
  ];

  console.log('Seeding measurement definitions...');

  for (const measurement of measurements) {
    await prisma.measurementDefinition.upsert({
      where: { name: measurement.name },
      update: measurement,
      create: measurement,
    });
  }

  console.log(`Successfully seeded ${measurements.length} measurement definitions`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });